version: '2'
services:
    faucet-postgresql:
        image: postgres:9.6.2
        volumes:
            - ~/volumes/faucet/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_DB=test-faucet
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admino0o0oo0
        ports:
            - 5432:5432